---
- name: Checking PAM configuration for root access
  ansible.builtin.shell: |
    grep -v ^# /etc/pam.d/su | grep -w auth | grep -w required | grep -w pam_wheel.so
  register: pam_su_config
  failed_when: false

- name: Set facts after checking.......    
  block:  
    - name: PASS if Configuration has been set to restrict root access to wheel group members only
      set_fact:
        check_pam_conf: "PASS"
      when: pam_su_config.stdout != ""

    - name: FAIL if Not yet configured to allow only users in the wheel group
      set_fact:
        check_pam_conf: "FAIL"
      when: pam_su_config.stdout == ""

- name: Detailed results are output after the checking process is finished....
  debug:
    msg: >
      {% if pam_su_config.stdout == "" %}
      [FAIL] Not yet configured to allow only users in the wheel group.
      {% else %}
      [PASS] Configuration has been set to restrict root access to wheel group members only
      {{ pam_su_config.stdout}}
      {% endif %}