---
- name: Check logrotate configuration for iptables
  shell: |
    #!/bin/bash
    entries=("/var/log/iptables/iptables.log" "{" "daily" "rotate 30" "copytruncate" "compress" "notifempty" "missingok" "}")
    for entry in "${entries[@]}"; do
        if grep -v ^# /etc/logrotate.d/iptables | grep -qw "$entry"; then
            echo "$entry [PASS]"
        else
            echo "$entry [FAIL]"
        fi
    done
  register: logrotate_check
  ignore_errors: true
  args:
    executable: /bin/bash

- name: Set facts after checking.......
  block:
    - name: PASS if all entries are PASS
      set_fact:
        check_logrotate_iptables: "PASS"
      when: "'[FAIL]' not in logrotate_check.stdout"

    - name: FAIL if any entry is FAIL
      set_fact:
        check_logrotate_iptables: "FAIL"
      when: "'[FAIL]' in logrotate_check.stdout"

- name: Detailed results are output after the checking process is finished....
  debug:
    msg: "{{ logrotate_check.stdout_lines }}"
