---
- name: Check SSH PermitRootLogin configuration
  ansible.builtin.shell: |
    grep -v ^# /etc/ssh/sshd_config | grep -w "PermitRootLogin no"
  register: permit_root_check
  failed_when: false  # Prevent task failure if grep returns non-zero exit code
  changed_when: false  # Prevent marking the task as changed

- name: Set facts after checking .....
  block:
    - name: PASS if PermitRootLogin is set to 'no'
      set_fact:
        check_permitRootLogin_conf: "PASS"
      when: permit_root_check.stdout != ""

    - name: FAIL if PermitRootLogin is not set to 'no'
      set_fact:
        check_permitRootLogin_conf: "FAIL"
      when: permit_root_check.stdout == ""
        
- name: Detailed results are output after the checking process is finished....
  ansible.builtin.debug:
    msg: >
      {{ 
        "[FAIL] PermitRootLogin is not set to 'no'" 
        if permit_root_check.stdout == "" 
        else 
        "[PASS] PermitRootLogin is correctly set to 'no'"
      }}